export const TYPES = {
  AGREGAR_AL_CARRITO: "AGREGAR_AL_CARRITO",
  ELIMINAR_UNO_DEL_CARRITO: "ELIMINAR_UNO_DEL_CARRITO",
  ELIMINAR_TODO_DEL_CARRITO: "ELIMINAR_TODO_DEL_CARRITO",
  LIMPIAR_EL_CARRITO: "LIMPIAR_EL_CARRITO",
};
